sudo: required

language: c

notifications:
  email: false

branches:
  only:
    - master
    - redborder
    - "/^[0-9]+\\.[0-9]+\\.[0-9]+/"

services:
  - docker

install:
  - pip install --user cpp-coveralls

script:
  - docker run -v $(pwd):/app redborder/build-dockerfiles:rb_monitor ./configure
  - docker run -v $(pwd):/app redborder/build-dockerfiles:rb_monitor make
  - docker run -v $(pwd):/app -e CFLAGS=-w redborder/build-dockerfiles:rb_monitor make tests -j 4

after_success:
  - docker run -v $(pwd):/app redborder/build-dockerfiles:rb_monitor make clean
  - docker run -v $(pwd):/app redborder/build-dockerfiles:rb_monitor ./configure --enable-coverage
  - docker run -v $(pwd):/app redborder/build-dockerfiles:rb_monitor make coverage
  - docker run -v $(pwd):/app redborder/build-dockerfiles:rb_monitor lcov --remove tests/coverage.info 'tests/*' '/usr/*' --output-file tests/coverage.info
  - docker run -v $(pwd):/app redborder/build-dockerfiles:rb_monitor lcov --list tests/coverage.info
  - coveralls --exclude /usr/lib --exclude tests --gcov-options '\-lp'

before_deploy:
  - tar -cvzf rb_monitor-${TRAVIS_TAG}.tar.gz rb_monitor

deploy:
  provider: releases
  api_key:
    secure: yJNiqNsVRWCIMeIATFjnucWFroG9bZ00JeoqB6h3vQgr4nnVawO4saTRG/q4dYwvUIMMq48WF9Aad2znAWegqrOhZEB+3Qne9XiYs9XAl5C9LiuVospZCmPlOhBWuTMHEewtFtJ6mfz8/UeT2ks+chxxTRrNrPBPriR40+nP4gg=
  file: rb_monitor-${TRAVIS_TAG}.tar.gz
  on:
    tags: true
